project_id = "kaebtbcufbpkhyrhuson"

[functions.create-test-admin]
verify_jwt = false

[functions.send-welcome-sms]
verify_jwt = false

[functions.send-offer-sms]
verify_jwt = false

[functions.export-campaign-anonymous]
verify_jwt = false
